import AdminHeader from "@/components/admin/AdminHeader";
import { SidebarInset } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dreamcots | admin",
  description: "Generated by create next app",
};

export default function AdminSubLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarInset>
      <AdminHeader />

      {children}
    </SidebarInset>
  );
}
